trigger:
  - master

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/BigSolution.Build.Agent.Yaml.Pipeline.Templates
      ref: 'refs/heads/refactor-version-number'
      endpoint: github.com_emmanuelbenitez

extends:
  template: Pipelines/dotnet-nuget/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Validation.sln"