trigger:
  - master

variables:
  - name: IsPreRelease
    type: boolean
    value: true

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/BigSolution.Build.Agent.Yaml.Pipeline.Templates
      endpoint: github.com_emmanuelbenitez

extends:
  template: Pipelines/dotnet-nuget/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Validation.sln"
    Major: 2
    Minor: 0
    Patch: 0
    IsPreRelease: $(IsPreRelease)